"""Autogenerated orchestration gate."""

from typing import Mapping


def evaluate(context: Mapping[str, object]) -> bool:
    """Return True when gate conditions are satisfied."""
    required = context.get("required", 0)
    achieved = context.get("achieved", 0)
    return bool(achieved >= required and context.get("status") == "ready")


DESCRIPTION = 'Analysis stage must reach depth scores within the acceptable threshold.'
